// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.


class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiznLwE9fr68YUeXoGURE19MzBeP1hEQs',
    appId: '1:298687040355:web:143ada5ac79976e7c9a156',
    messagingSenderId: '298687040355',
    projectId: 'flutterchat-f243e',
    authDomain: 'flutterchat-f243e.firebaseapp.com',
    storageBucket: 'flutterchat-f243e.appspot.com',
    measurementId: 'G-9S5FP3Y3ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9lkhSRa4FulDG7CXlOK9TKEupAvOYyQk',
    appId: '1:298687040355:android:539ee11c6153413ec9a156',
    messagingSenderId: '298687040355',
    projectId: 'flutterchat-f243e',
    storageBucket: 'flutterchat-f243e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqsemxwefg-GupvOsD6tfRsme50BXNVZY',
    appId: '1:298687040355:ios:13dd4536cca90ba1c9a156',
    messagingSenderId: '298687040355',
    projectId: 'flutterchat-f243e',
    storageBucket: 'flutterchat-f243e.appspot.com',
    iosClientId: '298687040355-vefmv6c3u1pevb7qn6npefip593mhsci.apps.googleusercontent.com',
    iosBundleId: 'com.hino.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqsemxwefg-GupvOsD6tfRsme50BXNVZY',
    appId: '1:298687040355:ios:67c3f068f93adc1cc9a156',
    messagingSenderId: '298687040355',
    projectId: 'flutterchat-f243e',
    storageBucket: 'flutterchat-f243e.appspot.com',
    iosClientId: '298687040355-f2l2a6usqt7lcjldvpcrnbo0mkg1mnps.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );
}
